package hackathon.medhack.backend.utils;

import hackathon.medhack.backend.model.*;

import javax.mail.*;
import javax.mail.Message;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import java.time.LocalDate;
import java.time.chrono.ChronoLocalDate;
import java.util.Properties;

public class SendEmail {
    public static void sendConfirmationSignUpMail(User user) {
        // Put recipient’s address
        String to = user.getEmail();

        // Put sender’s address
        String from = "medsoft.info@MedSoft.com";
        final String username = "6ea52c2e1cdde4";//username generated by Mailtrap
        final String password = "6c2b8e6e838609";//password generated by Mailtrap

        // Paste host address from the SMTP settings tab in your Mailtrap Inbox
        String host = "sandbox.smtp.mailtrap.io";

        Properties props = new Properties();
        props.put("mail.smtp.auth", "true");
        props.put("mail.smtp.starttls.enable", "true");//it’s optional in Mailtrap
        props.put("mail.smtp.host", host);
        props.put("mail.smtp.port", "2525");// use one of the options in the SMTP settings tab in your Mailtrap Inbox

        // Get the Session object.
        Session session = Session.getInstance(props,
                new javax.mail.Authenticator() {
                    protected PasswordAuthentication getPasswordAuthentication() {
                        return new PasswordAuthentication(username, password);
                    }
                });

        try {
            // Create a default MimeMessage object.
            Message message = new MimeMessage(session);

            // Set From: header field
            message.setFrom(new InternetAddress(from));

            // Set To: header field
            message.setRecipients(Message.RecipientType.TO,
                    InternetAddress.parse(to));

            // Set Subject: header field
            message.setSubject("VaxSoft sign-up confirmation!");

            // Put the content of your message
            message.setText( "Bun venit pe platforma VaxSoft!\nContul tau a fost activat: \nNume-prenume: " +
                    user.getFirstName() + "-" + user.getLastName() +
                    "\nEmail: "+ user.getEmail() + "\nParola: "+user.getPassword()+ "\nNumar de telefon: " + user.getPhoneNumber() +
                    "\n ------------ \n" +
                    "Calde salutari, echipa VaxSoft!");

            // Send message
            Transport.send(message);

            System.out.println("Sent message successfully....");

        } catch (MessagingException e) {
            throw new RuntimeException(e);
        }
    }


    public static void sendVaccineMemo(String doctorEmail, String parentEmail, Child child, Vaccine vaccine) {
        // Put recipient’s address
        String to = parentEmail;

        // Put sender’s address
        String from = doctorEmail;
        final String username = "6ea52c2e1cdde4";//username generated by Mailtrap
        final String password = "6c2b8e6e838609";//password generated by Mailtrap

        // Paste host address from the SMTP settings tab in your Mailtrap Inbox
        String host = "sandbox.smtp.mailtrap.io";

        Properties props = new Properties();
        props.put("mail.smtp.auth", "true");
        props.put("mail.smtp.starttls.enable", "true");//it’s optional in Mailtrap
        props.put("mail.smtp.host", host);
        props.put("mail.smtp.port", "2525");// use one of the options in the SMTP settings tab in your Mailtrap Inbox

        // Get the Session object.
        Session session = Session.getInstance(props,
                new javax.mail.Authenticator() {
                    protected PasswordAuthentication getPasswordAuthentication() {
                        return new PasswordAuthentication(username, password);
                    }
                });

        try {
            // Create a default MimeMessage object.
            Message message = new MimeMessage(session);

            // Set From: header field
            message.setFrom(new InternetAddress(from));

            // Set To: header field
            message.setRecipients(Message.RecipientType.TO,
                    InternetAddress.parse(to));

            // Set Subject: header field
            message.setSubject("VaxSoft: Vaccin pentru " + child.getFirstName() + " " + child.getLastName() + "!");

            float age = vaccine.getAge();
            String luni;
            if(age < 12){
                age /= 12;
                luni = "luni";
            }
            else{

                age /= 12;
                luni = "ani";
            }
            // Put the content of your message
            message.setText( "Se apropie urmatorul vaccin pentru micutul tau "+
                    child.getFirstName() + " " + child.getLastName() + "." +
                    "\nNumele vaccinului: " + vaccine.getName() +
                    "\nAbreviere: " + vaccine.getAbbreviation() +
                    "\nVarsta recomandata: " + age + luni);

            // Send message
            Transport.send(message);

            System.out.println("Sent message successfully....");

        } catch (MessagingException e) {
            throw new RuntimeException(e);
        }
    }
}
